name: Scheduled Crawler

on:
  schedule:
    - cron: "0 4 * * *" # 每天UTC 4點 (台北12點)

jobs:
  crawler:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 設定 Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose -f mysql.yml up -d

      # Step 3: 等待 MySQL 啟動
      - name: Wait for MySQL to be ready
        run: |
          while ! docker exec mysql mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for database connection..."
            sleep 3
          done

      # Step 4: 執行爬蟲
      - name: api_scheduler.py
        run: |
          python api_scheduler.py

      # Step 5: 停止 Docker Compose
      - name: Stop Docker Compose
        run: |
          docker-compose mysql.yml down
