name: deployment

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
